settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: chat
  path: .
  commands:
    build:
        status: false
        method: go build
        args:
        - -o
    run:
        status: true
  watcher:
    extensions:
    - go
    - html
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
